[env]
TERM = "xterm-256color"

[font]
# size = 20
size = 24

[general]
working_directory = "/Users/james/repos"
import = [
  "themes/catppuccin_mocha.toml"
]

[font.normal]
family = "MesloLGL Nerd Font Mono"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
